### PR TITLE
Bug: Specifying a position with add_new_at: :top fails to insert at that position

### PR DESCRIPTION
**Pull request by brendon**
I've created a test that confirms the bug. Now I guess we figure out how to fix it.

### CODE REVIEW

**Comment by brendon** [comment]
Hi fella's. I'd like some feedback on this one as it breaks currently tested behaviour, though the existing behaviour is weird to begin with. Let me know if you need any more details. I suppose we'd bump the minor version if we released this?

**Comment by swanandp** [comment]
rbi failures are weird. I will look into them.

**Comment by brendon** [comment]
Yes, they seem to be intermittent? Or perhaps I'm thinking of another time. Thanks for taking a look. I don't use Rubinius so I'm not sure what's going on :)

**Comment by brendon** [comment]
Perhaps we're testing against an old version of `rbx` that is buggy? Is this one equivalent to `mri2.1.0`?

**Comment by brendon** [comment]
Just closed and reopened this one to see if the `rbx` test failure was transient.

**Comment by brendon** [comment]
Hi @swanandp, Rubinius seems to be a bit flaky with travis-ci. The latest test run just failed outright on installing the gems. Should we look at dropping support for that particular ruby franchise? It's certainly causing uncertainty in development.

**Comment by brendon** [comment]
Scratch that, it seems it's to do with the extra gems we're specifying for `rbx`. I've removed them in a PR: #225 so we'll see how that builds. I'll then update this with that and see.

**Comment by brendon** [comment]
This is super frustrating. One pass and one failure, same code! :) And nothing major changed between versions :( Do we just go ahead and merge this @swanandp, and put it down to a bad travis stack?

**Comment by swanandp** [comment]
This looks like an interesting problem to tack down, but let's go ahead an
merge this, since this is the right way to go.

**Comment by brendon** [comment]
Yea, I've emailed the travis support team. See the Rails 4.1 test passed in the last run, then the 5.0 test failed! I think it's some instability on their end honestly. I'll merge this and do an 0.8.0 release.

**Comment by brendon** [comment]
0.8.0 has been released and includes this change.

**Pull request merged**
