### PR TITLE
Refactor update_all_with_touch

### PR DESCRIPTION
**Pull request by ledestin**
Hi,

I've refactored `update_all_with_touch`. If you're curious to know the reasons for my choices, I explain everything in a blog post: https://rubyclarity.com/2017/06/acts_as_list-refactoring-part-3/

### CODE REVIEW

**Comment by brendon** [comment]
Hi @ledestin, I think this is ok. @swanandp, did you have any thoughts?

**Comment by brendon** [comment]
Thanks @swanandp, we can actually do this for him with the Squash and merge button if you like?

**Comment by swanandp** [comment]
@brendon I am inclined to give him a choice. What do you think?

**Comment by brendon** [comment]
Oh yes definitely. I was just meaning he doesn't have to do the squash himself if he wants it to go that way :)

**Comment by ledestin** [comment]
@swanandp @brendon I'm ok with the way it suits you, it's your project after all. Feel free to squash.

**Pull request merged**
