### PR TITLE
Use `ActiveSupport.on_load` to hook into ActiveRecord

### LINKED ISSUE #268: ActiveRecord associations are no longer required (even though belongs_to_required_by_default == true)
I'm using Rails 5.0.2, `belongs_to_required_by_default = true`.  I have tests that verify my important associations are required.

After upgrading from 0.8.2 to 0.9.5, the specs in my app that ensure associations are required began to fail.  I identified that it happened during the transition to 0.9.0.  I attempted to test this within acts_as_list, but was not successful.  Instead, I referenced act_as_list via local "path:" in my Gemfile and used git bisect on the cloned acts_as_list dir while testing via my app.  This led me to: `[4abf1371b243dbd3d924b74fc073e7da0952edbd] Improve load method (#240)` and  PR #240 by @brendon. There is a lot going on in there.  I'm hoping that @brendon may have an idea.

I had a similar experience with simple_token_authentication: https://github.com/gonzalo-bulnes/simple_token_authentication/issues/297.  The workaround I found for them does not work for acts_as_list.

I hope we can use what we learn to help each other.

### PR DESCRIPTION
**Pull request by rono23**
There is a weird behavior of config `belongs_to_required_by_default` on Rails 5.0.2 when gem is not playing nice with the rails hooks.

Fix #268 and related rails/rails#23589

### CODE REVIEW

**Comment by brendon** [comment]
Thanks for this @rono23. @swanandp, what do you think about using concerns for this? I'd prefer to see if we could do this without using concerns and just use plain Ruby instead.

@rono23, would you be interested in trying that? As per: https://github.com/plataformatec/devise/commit/c2c74b0a39238e7d997486814a1c8f75fdaf276f

**Comment by brendon** [comment]
@rono23, I couldn't directly work on your PR for some reason but I've made some changes here: https://github.com/swanandp/acts_as_list/tree/pr/271

Check that out and see if it still works in your project. If so, I can close this and merge that one instead :)

**Comment by rono23** [comment]
@brendon Thank you for your review and it also works on my project.

FYI, [here](https://github.com/swanandp/acts_as_list/blob/master/lib/acts_as_list/active_record/acts/no_update.rb#L5) is also using `ActiveSupport::Concern`.

**Comment by swanandp** [comment]
@rono23 Looks good, but let's not move to `ActiveSupport::Concern` yet.  We can discuss it in another PR — but it certainly isn't required here.

**Comment by brendon** [comment]
Haha! That slipped through the cracks :) Not sure how I didn't notice the concern on that no-update code. I'll close this and merge my PR instead then look at removing the Concern in the other code.

**Pull request closed without merging**
