### PR TITLE
Keep position when changing scope for add_new_at top

### LINKED ISSUE #138: Changing scope is inconsistent based on add_new_at
If `add_new_at` is set to `bottom` then items moved into a list because of scope changes are added at the requested position. If `add_new_at` is set to `top` then the items are always added at the top, regardless of the requested position.

This is important when you have a grid of items and want to support dragging between lists. In our use-case it makes more sense for `add_to_list_top` to work the same way as `add_to_list_bottom` and to respect the existing value of the position column. This would mean that truly new items would be added to the top, but items dragged between lists would stay in the position you dragged them to (because the position is already set).

### PR DESCRIPTION
**Pull request by k1w1**
This makes the behavior consistent with add_new_at: :bottom and fixes #138.

### CODE REVIEW

**Comment by brendon** [comment]
Hi @k1w1 (New Zealander?),

Let's get this one tidied up and merged. Can you rebase it and I'll take another look.

**Comment by brendon** [comment]
@k1w1, I'd like to get this one cleared out. Can you respond to let me know if you're able to keep working on this or should we close it for now?

**Comment by k1w1** [comment]
Hi. Sorry, we are no longer using this fork of acts_as_list and it has been so long I can't remember why I wrote the code like I did. 

We made a new fork (https://github.com/aha-app/acts_as_list) which works in a radically different way which is atomic at the DB level. This was to solve persistent, but rare, problems that we think were caused by race conditions when multiple processes were updating the same list.

**Comment by brendon** [comment]
Thanks @k1w1. How divergent from the current code base is that fork? We're always interested in bringing in better code where possible. I think it'd be better to have your more robust code in the main gem vs a fork if you were keen on helping merge it. What do you think?

**Comment by k1w1** [comment]
The feature set in our branch is significantly reduced. We only implemented the features we needed. The problem we had with this repo is that occasionally we would end up with multiple items with the same position value (we think via race conditions). Once that happened it was impossible for a user to fix by dragging items around. We switched to an implementation that is *postgres specific*, but is atomic in the updates, and also self-corrects if things get messed up somehow.

Unfortunately I don't think it is easily generalizable.

**Comment by brendon** [comment]
Thanks Chris :) That makes sense to me. I guess this is here in case anyone else faces a similar need to yourselves. We're looking into atomic updates but I don't think it's feasible on MySQL etc... unfortunately.

**Pull request closed without merging**
