### PR TITLE
Fix Fixnum deprecation warnings.

### PR DESCRIPTION
**Pull request by patrickdavey**
Fixnum is being deprecated and merged with Bignum into Integer
(http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html)

This PR replaces Fixnum with Integer (in the tests) and fixes the
deprecation warnings

### CODE REVIEW

**Comment by brendon** [comment]
Excellent! :) Thanks @patrickdavey.

**Comment by krzysiek1507** [comment]
What's the file `file:memdb1?mode=memory&cache=shared`? ;)

**Comment by brendon** [comment]
I can't quite remember but you can use the blame feature of github to find out what the related commit was. I think it was to do with simulating race conditions.

**Comment by krzysiek1507** [comment]
It has added with this PR and it looks like SQLite file.

**Comment by brendon** [comment]
Not according to the files list: https://github.com/swanandp/acts_as_list/pull/282/files

**Comment by krzysiek1507** [comment]
I can see it. 

screenshot-github com 2017-07-02 23-02-56

**Comment by brendon** [comment]
Ah I see! Sorry it doesn't really stand out at all in the list does it. I've committed a removal directly to master.

**Comment by krzysiek1507** [comment]
No problem! Thanks!

**Comment by patrickdavey** [comment]
My apologies for that :( I should have been more careful, usually am but it slipped through! Thanks @krzysiek1507 for pointing that out, and @brendon for fixing it.

**Comment by brendon** [comment]
Hey no worries :D We haven't released a gem yet anyway :)

**Pull request merged**
