### PR TITLE
Failing example for #153

### PR DESCRIPTION
**Pull request by afn**

### CODE REVIEW

**Comment by brendon** [comment]
Thanks for this, could you rebase it please and check that the bug still exists? Also, the CI tests are failing due to an arity problem. Can you fix that up too please? It could be that you have to adjust your tests to take into account that we test against Rails 3.2+

**Comment by brendon** [comment]
Hi @afn, can you rebase this?

**Comment by afn** [comment]
Rebased against master.

**Comment by brendon** [comment]
Thanks @afn, the test suite seems to be failing due to a syntax error. Can you see if you can get it to run again? See the Travis results below.

**Comment by brendon** [comment]
@afn, your `ActiveRecord::Base.logger = Logger.new STDOUT` line is causing an error. Might have to make it absolute `::Logger` :)

**Comment by afn** [comment]
Sorry for the delay — fixed the syntax error.

**Pull request closed without merging**
