### PR TITLE
Don't require rails when loading

### LINKED ISSUE #145: Can no longer load acts_as_list in isolation if Rails is installed
Hello, thanks for maintaining acts_as_list!

I like to unit test my models in isolation from rails, but this is no longer possible if the model depends on acts_as_list, since `require 'acts_as_list'` now requires rails, as of https://github.com/swanandp/acts_as_list/pull/114 . Simplest solution would be to revert the PR, but it'd be nice to get the best of both worlds. Could we replace `require 'rails'` with a test for `defined?(Rails)`, or something similar? \cc @amatsuda

### PR DESCRIPTION
**Pull request by botandrose**
Fixes #145.

### CODE REVIEW

**Comment by botandrose** [comment]
Failure appears to be a red herring. Rubinius can't find 'psych'... pretty sure that's unrelated to this PR.

**Comment by amatsuda** [comment]
As an author of #114, I can confirm that this change does no harm to typical users that use bundler to run their rails apps.
Because config/application.rb executes `require 'rails'`[here](https://github.com/rails/rails/blob/864c6409659ba42c78abd82e369f095517dd42be/railties/lib/rails/generators/rails/app/templates/config/application.rb#L4) before [bundling the gems](https://github.com/rails/rails/blob/864c6409659ba42c78abd82e369f095517dd42be/railties/lib/rails/generators/rails/app/templates/config/application.rb#L20), `Rails::Railtie` should always be already defined when requiring acts_as_list.rb
So this PR is OK to merge.

**Comment by swanandp** [comment]
Looks good to me as well, thanks @botandrose for contributing, and @amatsuda for reviewing!

**Comment by botandrose** [comment]
Thanks, everyone!

**Pull request merged**
